teste = input('Digite algo:')
print('O tipo desse caracter é ',type(teste))
print('Só tem espaço? ',teste.isspace())
print('É um número? ',teste.isnumeric())
print('É uma letra?',teste.isalpha())
print('Possui letra e número?',teste.isalnum())
print('Tem maiúsculas?',teste.isupper())
print('Tem minúsculas?',teste.islower())
print('Tem maiúsculas e minúsculas?',teste.istitle())
